---
stages:
  - test
  - docker

build:
  stage: test
  image: golang
  script:
    - go build -v ./...

test:
  stage: test
  image: golang
  script:
    - go test -v ./...

golangci-lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - golangci-lint run

docker:
  stage: docker
  script:
    - echo Building dockerfile as $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:=${CI_COMMIT_SHORT_SHA:=${CI_COMMIT_SHA:0:8}}}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push -a $CI_REGISTRY_IMAGE
  tags:
    - docker
  only:
    refs:
      - tags
      - master
