---
stages:
  - lint
  - test
  - docker

golangci-lint:
  stage: lint
  image: golangci/golangci-lint
  script:
    - golangci-lint run --timeout 5m

test:
  stage: test
  image: golang
  script:
    - go test -v ./...

lab:
  stage: test
  image: golang
  variables:
    name: domain.tld
  before_script:
    - apt-get update
    - apt-get install -y jq curl openssl
  script:
    - test/test.sh "${name}"

docker:
  stage: docker
  script:
    - echo Building dockerfile as $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:=${CI_COMMIT_SHORT_SHA:=${CI_COMMIT_SHA:0:8}}}
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY_IMAGE
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push -a $CI_REGISTRY_IMAGE
  tags:
    - docker
  only:
    refs:
      - tags
      - master
